### PR TITLE
Updated SHA256 for UltraVNC 1.2.24

### PR DESCRIPTION
**Pull request by lefte**
UltraVNC - Updated SHA256 hashes for UltraVNC v1.2.24

## Description
Updated SHA256 hashes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by mkevenaar** [comment]
Hi, Thanks for your PR and noticing that the checksums are incorrect. I have triggered a new build and forced UltraVNC. This should resolve this automatically.

**Comment by mkevenaar** [comment]
A new version is pushed: https://chocolatey.org/packages/ultravnc/1.2240.0.20190403

**Comment by mkevenaar** [comment]
Thank you for your contribution!

**Comment by lefte** [comment]
> Thank you for your contribution!

I appreciate it! In the future, what is the best way to notify you to trigger a new build? Would you prefer that I open an issue here in GitHub? Thanks for the help

**Comment by mkevenaar** [comment]
Yep that would be great, thank you!

**Comment by Neustradamus** [comment]
Dear all, @mkevenaar,

I have done a ticket to have a fix about bad UltraVNC version numbers in Chocolatey:
- https://github.com/mkevenaar/chocolatey-packages/issues/276

In more, I have done a ticket one year ago about 1.4.3.6:
- https://github.com/mkevenaar/chocolatey-packages/issues/222

**Pull request closed without merging**
