### PR TITLE
Update PowerToys script to newer tag

### PR DESCRIPTION
**Pull request by jaimecbernardo**
## Description

Updates the PowerToys install script for the new tag for 0.82.1: "v0.82.1" (notice lowercase "v")

## Motivation and Context

I'm a dev lead in PowerToys. Proof in : https://github.com/microsoft/PowerToys/blob/main/COMMUNITY.md#powertoys-core-team

image

We wrongly released the 0.82.1 tag as "V0.82.1" instead of "v0.82.1". We've just corrected that. Downloads should now contain lowercase "v": https://github.com/microsoft/PowerToys/releases/tag/v0.82.1

This PR reflects that correction.

## How Has this Been Tested?

Links work with lowercase tag.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/mkevenaar/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by jaimecbernardo** [comment]
CI failed saying Authentication failed? 🤔 I assume that's not related to the contents of this PR.

**Comment by jaimecbernardo** [comment]
@mkevenaar

**Comment by flcdrg** [comment]
Can confirm current Chocolatey package is broken as it is using the wrong cased 'v' in the download link.

**Comment by mkevenaar** [comment]
Unfortunately, this is not the solution. I have fixed it in https://github.com/mkevenaar/chocolatey-packages/commit/80c4d99cc8faab688d290758e81e96de61b623b3. A new version, with package fix notation, has been approved on Chocolatey: https://community.chocolatey.org/packages/powertoys/0.82.1.20240716

**Pull request closed without merging**
