### PR TITLE
(sqlitebrowser.install) Enable Start menu shortcuts

### LINKED ISSUE #28: (sqlitebrowser.install) lacks of Start Menu shortcut
## Expected Behavior

Start Menu shortcut can be found in Start Menu after installation.

## Current Behavior

There is no shortcut to [_DB browser for SQLite_](https://github.com/mkevenaar/chocolatey-packages/tree/master/automatic/sqlitebrowser.install) in startup menu. It is needed to locate the program on disk and create shortcut manually and place it to Start Menu.

## Possible Solution

[Create shortcut](https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyShortcut) with installation script.

### PR DESCRIPTION
**Pull request by mwisnicki**
## Description
Until upstream fixes sqlitebrowser/sqlitebrowser#2460 this is the best we can do.

## Motivation and Context
Fix #28 aka sqlitebrowser/sqlitebrowser#2458

## How Has this Been Tested?
Run it locally.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/mkevenaar/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by mwisnicki** [comment]
Someone else will need to finish the checklist and bump nuspec version.

**Comment by mkevenaar** [comment]
@mwisnicki I added the possibility to disable the shortcuts, and added the desktop shortcuts. Default enabled.
I am waiting for the build to finish before I merge this.

**Review by mkevenaar — APPROVED** [review]
LGTM!

**Comment by mkevenaar** [comment]
@mwisnicki your changes have been merged, a new version of sqlitebrowser / .install have  been pushed and should be available shortly.

Thank you for your contribution!

**Pull request merged**
