### PR TITLE
(nsis) new download url [AU nsis.install]

### PR DESCRIPTION
**Pull request by riezebosch**
certificate for current is expired

## Description

Empty commit to force update from `au`.

## How Has this Been Tested?

Screen Shot 2020-01-06 at 08 40 01

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ x] All files are up to date with the latest [Contributing Guidelines](https://github.com/mkevenaar/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by riezebosch** [comment]
Old url: https://svwh.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe
New url: https://netix.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe

**Comment by riezebosch** [comment]
Done. Digging through the logs of appveyor I did not see the package actually being updated.

**Comment by mkevenaar** [comment]
@riezebosch Thanks for your contribution, your changes have been merged 👍

**Comment by riezebosch** [comment]
The download url resolved by the update scripts is again different: https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe

No clue what's the reasoning behind it, at least this one works 😕

**Comment by bitlogik** [comment]
Worked until today. astuteinternet.dl.sourceforge.net is expired. Latest approved nsis package version (calls nsis.install/3.5.0.20200106) on chocolately is broken. Meaning choco install nsis doesn't work from today.

**Comment by mkevenaar** [comment]
@bitlogik A new version of the package is already available and waiting for moderators to approve: https://chocolatey.org/packages/nsis.install/3.06.1

The new version embeds the installer inside the package so this never happens again.

**Comment by atmalpa** [comment]
3.06.1 version is still in "ready for review" state. 3.5 version has hardcoded url to sourceforge server which certificate expired so it's unable to install nsis using choco since 8th of August...

**Comment by bitlogik** [comment]
"review" or not, it is accessible as any other versions using :
`choco install -y nsis   --version=3.06.1`

About the SourceForge issue, [we opened a ticket](https://sourceforge.net/p/forge/site-support/21088/). They say that "mirrors are rather volatile and can activate/deactivate depending on network health and mirror agreements. Linking to specific mirrors is not recommended. The recommended approach is to use the general direct download link at downloads.sourceforge.net. If visited with wget, curl, or any automated tool, it will respond with a redirect link to a valid and active mirror."
The issue with SourceForge was resolved here because it doesn't use SF anymore. I just recall it in case (if one author requires its software must be dl from SF only), that the global URL downloads.sourceforge.net must be used, along with a redirection handling.

**Pull request merged**
