### PR TITLE
(jetbrainstoolbox) fixed new silent parameters for installer

### LINKED ISSUE #236: (jetbrainstoolbox) update fails with timeout
## Expected Behavior
Should update without errors

## Current Behavior
installation times out 

## Steps to Reproduce (for bugs)
1. `choco upgrade jetbrainstoolbox`

## Your Environment
* Package Version used: 2.3.0.30876
* Operating System and version:  Windows 23H2 10.0.22631.0
* Chocolatey version: 2.2.2
* Install/uninstall gist:
```
Chocolatey v2.2.2
Upgrading the following packages:
jetbrainstoolbox
By upgrading, you accept licenses for the packages.

You have jetbrainstoolbox v2.2.3.20090 installed. Version 2.3.0.30876 is available based on your source(s).
Progress: Downloading jetbrainstoolbox 2.3.0.30876... 100%

jetbrainstoolbox v2.3.0.30876 [Approved]
jetbrainstoolbox package files upgrade completed. Performing other installation steps.
The package jetbrainstoolbox wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing jetbrainstoolbox...
Chocolatey timed out waiting for the command to finish. The timeout
 specified (or the default value) was '2700' seconds. Perhaps try a
 higher `--execution-timeout`? See `choco -h` for details.
The upgrade of jetbrainstoolbox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\jetbrainstoolbox\tools\chocolateyinstall.ps1'.
 See log for details.
 Unsuccessful operation for jetbrainstoolbox.
  Rollback to previous version (package files only)?([Y]es/[N]o):
```

### PR DESCRIPTION
**Pull request by FibreFoX**
installer got changed, see https://youtrack.jetbrains.com/issue/TBX-3219/Toolbox-App-silent-install for more details

## Description
Changed the install parameters for silent install to have this package working again

## Motivation and Context
Should fix #236

## How Has this Been Tested?
Running the new installer with old and new parameters "by hand".

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

### CODE REVIEW

**Comment by FibreFoX** [comment]
I have no idea how to fix this ... was this even working before? Is this a false-positive?

**Comment by mkevenaar** [comment]
@FibreFoX 

I have restarted the tests. It failed to download a package.

**Review by mkevenaar — APPROVED** [review]
LGTM!

**Comment by mkevenaar** [comment]
@FibreFoX, your changes have been merged; thank you for your contribution! 

This will be available on the next version of JetBrains ToolBox.

**Pull request merged**
