### PR TITLE
Moving these packages from my repository to yours as you are taking them over.

### PR DESCRIPTION
**Pull request by JourneyOver**
https://github.com/chocolatey-community/chocolatey-package-requests/issues/1498 https://github.com/chocolatey-community/chocolatey-package-requests/issues/1499 https://github.com/chocolatey-community/chocolatey-package-requests/issues/1506 https://github.com/chocolatey-community/chocolatey-package-requests/issues/1507 https://github.com/chocolatey-community/chocolatey-package-requests/issues/1505

## Description

Moving these packages from my repository to yours as you are taking them over.

## Motivation and Context

You are taking over these packages ^^

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Migrated package (a package has been migrated from another repository) (multiple)

## Checklist: (not sure if I should fill this out or not as it's multiple packages in a single PR)

- [ ] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/mkevenaar/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by JourneyOver** [comment]
Thanks again for taking these over, will be removing them from my repo as of now. I'm going to move over the single issue I had on my repo as well that I had remaining for at least sonarr once this gets accepted.

**Comment by mkevenaar** [comment]
@JourneyOver I am working on getting the packages to my standard. Feel free to disable the packages from your repository. Please do not (yet) delete the repo/packages/icons

Thank you for all the time you maintained those packages!

**Comment by JourneyOver** [comment]
> @JourneyOver I am working on getting the packages to my standard. Feel free to disable the packages from your repository. Please do not (yet) delete the repo/packages/icons

yea I had previously deleted them after pushing them over to this PR but I just added them back into my repo again today but with the update scripts completely disabled for the packages. I'll probably just leave all packages in my repo as more and more of my packages get taken over but just go about disabling the update scripts until the last one is taken over and then I'll archive my repo.

> Thank you for all the time you maintained those packages!

it's not a problem :) I used pretty much all these (short of jackett since I moved to prowlarr when it was released) but over the past 2 years I've been moving a lot of stuff over to linux/docker setups for a lot of programs I use so I've kind of neglected things like chocolatey and such especially since I don't really have the time to really keep up maintenance much anymore between multiple projects and various other things going on in life :x 

but I do thank you for taking over these packages ^^

**Review by mkevenaar — APPROVED** [review]

**Comment by mkevenaar** [comment]
@JourneyOver I have merged the changes just now, thank you for your contribution!

**Comment by JourneyOver** [comment]
Perfect, thanks a bunch once again for taking all these over ^^

**Pull request merged**
